"""add login auth fields

Revision ID: 5e45f5344ed9
Revises: a1b2c3d4e5f7
Create Date: 2026-01-07 13:29:29.523031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e45f5344ed9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_unique_constraint('uq_users_login', 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_login', 'users', type_='unique')
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
