"""add transactions

Revision ID: 7c1251383d2a
Revises: f9d93f3a16ae
Create Date: 2025-12-15 05:09:48.604424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1251383d2a'
down_revision: Union[str, Sequence[str], None] = 'f9d93f3a16ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('primary_item_id', sa.BigInteger(), nullable=False),
    sa.Column('counterparty_item_id', sa.BigInteger(), nullable=True),
    sa.Column('amount_rub', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('category_l1', sa.String(length=100), nullable=False),
    sa.Column('category_l2', sa.String(length=100), nullable=False),
    sa.Column('category_l3', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction in ('INCOME','EXPENSE','TRANSFER')", name='ck_transactions_direction'),
    sa.CheckConstraint("transaction_type in ('ACTUAL','PLANNED')", name='ck_transactions_type'),
    sa.CheckConstraint('amount_rub >= 0', name='ck_transactions_amount_non_negative'),
    sa.ForeignKeyConstraint(['counterparty_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['primary_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
