"""add deleted_at to transactions

Revision ID: cee01bb4abb2
Revises: 7c1251383d2a
Create Date: 2025-12-15 06:00:46.906945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee01bb4abb2'
down_revision: Union[str, Sequence[str], None] = '7c1251383d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deleted_at')
    # ### end Alembic commands ###
