import type { ComponentType, CSSProperties } from "react";
import {
  Ban,
  BadgePercent,
  Baby,
  Banknote,
  BanknoteArrowUp,
  Bike,
  Bone,
  BottleWine,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Car,
  CalendarSync,
  Calculator,
  ChefHat,
  Cigarette,
  CirclePercent,
  Coffee,
  Coins,
  CreditCard,
  Droplet,
  Droplets,
  Dumbbell,
  Film,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Landmark,
  Lightbulb,
  MapPin,
  Mic,
  Music,
  MoreVertical,
  PawPrint,
  Percent,
  PiggyBank,
  Plane,
  Popcorn,
  Paintbrush,
  Palette,
  Phone,
  Pill,
  Pizza,
  Pyramid,
  Receipt,
  Scissors,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shield,
  Shirt,
  Smartphone,
  Sparkles,
  Stethoscope,
  Syringe,
  Ticket,
  Train,
  TrendingUp,
  Truck,
  Undo2,
  Utensils,
  Tv,
  Wifi,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

type CategoryIcon = ComponentType<{
  className?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}>;

export const CATEGORY_ICON_FALLBACK: CategoryIcon = PiggyBank;

export const CATEGORY_ICON_BY_NAME: Record<string, CategoryIcon> = {
  Briefcase,
  Hammer,
  TrendingUp,
  Percent,
  BadgePercent,
  Baby,
  Coins,
  Banknote,
  BanknoteArrowUp,
  Wallet,
  Landmark,
  Calculator,
  Car,
  Bike,
  Truck,
  Train,
  Ship,
  Building,
  Wrench,
  ShieldCheck,
  Heart,
  Sparkles,
  Gamepad2,
  Music,
  Headphones,
  Mic,
  BookOpen,
  GraduationCap,
  Paintbrush,
  Palette,
  Wifi,
  Phone,
  Smartphone,
  PawPrint,
  Bone,
  BottleWine,
  HandCoins,
  CreditCard,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Receipt,
  Shirt,
  ShoppingCart,
  ShoppingBag,
  Coffee,
  ChefHat,
  Pizza,
  Popcorn,
  Film,
  Plane,
  MapPin,
  Ticket,
  Tv,
  Lightbulb,
  Zap,
  Droplet,
  Dumbbell,
  Ban,
  Cigarette,
  Utensils,
  CalendarSync,
  Gift,
  Shield,
  Bus,
  Scissors,
  Home,
  Laptop,
  MoreVertical,
  Undo2,
  Pyramid,
  Droplets,
  CirclePercent,
};

const CATEGORY_ICON_OPTION_NAMES = [
  "Briefcase",
  "Hammer",
  "TrendingUp",
  "Percent",
  "BadgePercent",
  "Baby",
  "Coins",
  "Banknote",
  "BanknoteArrowUp",
  "Wallet",
  "Landmark",
  "Calculator",
  "Car",
  "Bike",
  "Truck",
  "Train",
  "Ship",
  "Building",
  "Wrench",
  "ShieldCheck",
  "Heart",
  "Sparkles",
  "Gamepad2",
  "Music",
  "Headphones",
  "Mic",
  "BookOpen",
  "GraduationCap",
  "Paintbrush",
  "Palette",
  "Wifi",
  "Phone",
  "Smartphone",
  "PawPrint",
  "Bone",
  "BottleWine",
  "HandCoins",
  "CreditCard",
  "HeartPulse",
  "Stethoscope",
  "Pill",
  "Syringe",
  "Receipt",
  "Shirt",
  "ShoppingCart",
  "ShoppingBag",
  "Coffee",
  "ChefHat",
  "Pizza",
  "Popcorn",
  "Film",
  "Plane",
  "MapPin",
  "Ticket",
  "Tv",
  "Lightbulb",
  "Zap",
  "Droplet",
  "Dumbbell",
  "Ban",
  "Cigarette",
  "Utensils",
  "CalendarSync",
  "Gift",
  "Shield",
  "Bus",
  "Scissors",
  "Home",
  "Laptop",
  "MoreVertical",
  "Undo2",
  "Pyramid",
  "Droplets",
  "CirclePercent",
] as const;

export const CATEGORY_ICON_OPTIONS = CATEGORY_ICON_OPTION_NAMES.map((name) => ({
  value: name,
  label: name,
  Icon: CATEGORY_ICON_BY_NAME[name],
}));

export const CATEGORY_ICON_BY_L1: Record<string, CategoryIcon> = {
  "Доход от основного места работы": Briefcase,
  "Доход от подработок": Hammer,
  "Пассивный доход": Percent,
  "Бонусы и Cash-back": BanknoteArrowUp,
  "Прочие доходы": Coins,
  "Социальные выплаты": Landmark,
  "Алименты полученные": HandCoins,
  "Личный транспорт": Car,
  "Недвижимость": Building,
  "Услуги": Wrench,
  "Благотворительность": Heart,
  "Дети": Baby,
  "Образование": GraduationCap,
  "Хобби и увлечения": Gamepad2,
  "Интернет и связь": Wifi,
  "Домашние животные": PawPrint,
  "Кредиты": HandCoins,
  "Здоровье": HeartPulse,
  "Налоги": Receipt,
  "Одежда и обувь": Shirt,
  "Отдых и развлечения": Popcorn,
  "Путешествия": Plane,
  "Вредные привычки": Cigarette,
  "Питание": Utensils,
  "Подписки": CalendarSync,
  "Подарки": Gift,
  "Алименты оплаченные": HandCoins,
  "Страхование": Shield,
  "Транспорт": Bus,
  "Уход за собой": Scissors,
  "Хозяйственные расходы": Home,
  "Прочие расходы": MoreVertical,
  "Комиссии": Receipt,
  "Парфюмерия": Droplets,
  "Tax-free": CirclePercent,
};

const CATEGORY_ICON_NAME_BY_COMPONENT = new Map<CategoryIcon, string>(
  Object.entries(CATEGORY_ICON_BY_NAME).map(([name, Icon]) => [Icon, name])
);

export const CATEGORY_ICON_NAME_BY_L1: Record<string, string> = Object.fromEntries(
  Object.entries(CATEGORY_ICON_BY_L1)
    .map(([label, Icon]) => [label, CATEGORY_ICON_NAME_BY_COMPONENT.get(Icon)])
    .filter(([, iconName]) => Boolean(iconName))
) as Record<string, string>;
