import { ItemOut } from "@/lib/api";

export const ITEM_TYPE_LABELS: Record<string, string> = {
  cash: "Наличные",
  bank_account: "Банковский счёт",
  bank_card: "Банковская карта",
  savings_account: "Накопительный счет",
  e_wallet: "Электронный кошелек",
  brokerage: "Брокерский счёт",
  deposit: "Вклад",
  securities: "Акции",
  bonds: "Облигации",
  etf: "ETF",
  bpif: "БПИФ",
  pif: "ПИФ",
  iis: "ИИС",
  precious_metals: "Драгоценные металлы",
  crypto: "Криптовалюта",
  loan_to_third_party: "Предоставленные займы третьим лицам",
  third_party_receivables: "Долги третьих лиц",
  real_estate: "Квартира",
  townhouse: "Дом / таунхаус",
  land_plot: "Земельный участок",
  garage: "Гараж / машиноместо",
  commercial_real_estate: "Коммерческая недвижимость",
  real_estate_share: "Доля в недвижимости",
  car: "Автомобиль",
  motorcycle: "Мотоцикл",
  boat: "Катер / лодка",
  trailer: "Прицеп",
  special_vehicle: "Спецтехника",
  jewelry: "Драгоценности",
  electronics: "Техника и электроника",
  art: "Ценные предметы искусства",
  collectibles: "Коллекционные вещи",
  other_valuables: "Прочие ценные вещи",
  npf: "НПФ",
  investment_life_insurance: "ИСЖ",
  business_share: "Доля в бизнесе",
  sole_proprietor: "ИП (оценка бизнеса)",
  other_asset: "Прочие активы",
  credit_card_debt: "Задолженность по кредитной карте",
  consumer_loan: "Потребительский кредит",
  mortgage: "Ипотека",
  car_loan: "Автокредит",
  education_loan: "Образовательный кредит",
  installment: "Рассрочка",
  microloan: "МФО",
  private_loan: "Полученные займы от третьих лиц",
  third_party_payables: "Долги третьим лицам",
  tax_debt: "Налоги и обязательные платежи",
  personal_income_tax_debt: "Задолженность по НДФЛ",
  property_tax_debt: "Задолженность по налогу на имущество",
  land_tax_debt: "Задолженность по земельному налогу",
  transport_tax_debt: "Задолженность по транспортному налогу",
  fns_debt: "Задолженности перед ФНС",
  utilities_debt: "Задолженность по ЖКХ",
  telecom_debt: "Задолженность за интернет / связь",
  traffic_fines_debt: "Задолженность по штрафам (ГИБДД и прочие)",
  enforcement_debt: "Задолженность по исполнительным листам",
  alimony_debt: "Задолженность по алиментам",
  court_debt: "Судебные задолженности",
  court_fine_debt: "Штрафы по решениям суда",
  business_liability: "Бизнес-обязательства",
  other_liability: "Прочие обязательства",
};

export function getItemTypeLabel(item: ItemOut) {
  const base = ITEM_TYPE_LABELS[item.type_code] ?? item.type_code;
  if (item.type_code === "bank_card") {
    if (item.card_kind === "CREDIT") return `${base} (кредитная)`;
    if (item.card_kind === "DEBIT") return `${base} (дебетовая)`;
  }
  return base;
}
